//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasQueueProcessor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniCanvasNotasAuditoria
    {
        public int NroMensaje { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CantNotas { get; set; }
    }
}
